# H2
dataSource:
    jdbc:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./live
        username: sa
        password:
# PostgreSQL
#       driverClassName=org.postgresql.Driver
#       url=jdbc:postgresql://localhost/tomcatdb
#       username=test
#       password=g6p8
# HSQLDB
# Server
#       driverClassName=org.hsqldb.jdbcDriver
#       url=jdbc:hsqldb:hsql://localhost
#       username=sa
#       password=
# Memory
#       driverClassName=org.hsqldb.jdbcDriver
#       url=jdbc:hsqldb:mem:.
#       username=SA
#       password=
# File
#       driverClassName=org.hsqldb.jdbcDriver
#       url=jdbc:hsqldb:file:./live;hsqldb.write_delay=false;shutdown=true
#       username=SA
#       password=
    liquibase:
        changeLog: classpath:liquibase/master.xml
        contexts: test, production
        defaultSchema: public
        dropFirst: false
    jpa:
        persistenceUnitName: default
        persistenceXmlPath: classpath:META-INF/persistence.xml
